site_name: Gedankenspiele
site_url: https://backlundt.github.io/blog/
theme:
  name: simple-blog

nav:
  - Home: index.md
  - Blog: 
      - blog/22.3.25.md
      - blog/29.06.25.md
  - About: about.md

extra:
  blog_dir: blog  # Optional: used for breadcrumb generation or links
  author: Andreas Volkhardt
  description: A minimal blog using MkDocs

markdown_extensions:
  - meta
  - toc:
      permalink: true
