name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - master  # or your default branch

permissions:
  contents: write  # Required for pushing to gh-pages

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MkDocs
        run: |
          pip install mkdocs

      - name: Deploy with MkDocs
        run: cd qndes-homepage && mkdocs gh-deploy --force
