name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - master  # or your default branch

permissions:
  contents: write  # Required for pushing to gh-pages

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs

      - name: Deploy with MkDocs
        run: cd qndes-homepage && mkdocs gh-deploy --force
